CREATE PROCEDURE dbo.TPW_SERVICE_PUMP_PJOB
(
	@outSwitch_To_Mode	NVARCHAR(8)	OUTPUT
)
AS
	/* SET NOCOUNT ON */
	DECLARE	@tReturn	INT;
	DECLARE	@tNow		DATETIME;
	
	SET	@tNow	= GETDATE();

	UPDATE	TPW_PUMP_CONFIG
	SET		DATE_VALUE		= @tNow
	WHERE	ELEMENT_NAME	= N'PRIMARY_BEAT';

	EXEC @tReturn = TPW_SERVICE_ARCHIVE_PJOB;
	IF @tReturn > 0
		EXEC TPW_SERVICE_EXPIRE_PJOB;

	SELECT
		PJOB_ID
	FROM
		VIEW_TPW_PJOB_STATE_MACHINE
	WHERE
			SCHEDULED_TIME	<= @tNow
		AND EVENT_NAME		= N'RUN'			-- Can run
	ORDER BY
		PJOB_ID;

	SET	@outSwitch_To_Mode	= N'Primary';

	EXEC TPW_SERVICE_SERVICE_PING 1;
