CREATE PROCEDURE dbo.TPW_SERVICE_COMPLETE_PJOB
(
	@inPJob_ID	INT
)
AS
	SET NOCOUNT ON;
	DECLARE	@tReturn	INT;

	EXEC @tReturn = TPW_SERVICE_ON_PJOB_EVENT @inPJob_ID, N'COMPLETE';
	IF @tReturn < 0
		RETURN @tReturn;

	UPDATE	TPW_PJOB
	SET		END_TIME	= GETDATE()
	WHERE	END_TIME	IS NULL
		AND	PJOB_ID		= @inPJob_ID;
