CREATE PROCEDURE dbo.TPW_SERVICE_RUN_PJOB
(
	@inPJob_ID	INT
)
AS
	/* SET NOCOUNT ON */
	DECLARE	@tReturn	INT;

	EXEC @tReturn = TPW_SERVICE_ON_PJOB_EVENT @inPJob_ID, N'RUN';
	IF @tReturn < 0
		RETURN @tReturn;

	UPDATE	TPW_PJOB
	SET		START_TIME	= GETDATE()
	WHERE	PJOB_ID		= @inPJob_ID;

	SELECT
		PJOB_ID,
		TASK_ID,
		COMMAND_TIMEOUT
	FROM
		TPW_TASK
	WHERE
		PJOB_ID	= @inPJob_ID;
