CREATE PROCEDURE dbo.TPW_SERVICE_GET_SERVICE_CONFIG
(
	@outPrimary_Interval			TINYINT	OUTPUT,
	@outStandby_Interval			TINYINT	OUTPUT,
	@outDegree_Task_Parallelism		TINYINT	OUTPUT,
	@outMax_Threads_In_Pool			TINYINT	OUTPUT
)
AS
	SET NOCOUNT ON;

	SELECT @outPrimary_Interval			= NUMBER_VALUE FROM TPW_PUMP_CONFIG WHERE ELEMENT_NAME = N'PRIMARY_INTERVAL';
	SELECT @outStandby_Interval			= NUMBER_VALUE FROM TPW_PUMP_CONFIG WHERE ELEMENT_NAME = N'STANDBY_INTERVAL';
	SELECT @outDegree_Task_Parallelism	= NUMBER_VALUE FROM TPW_PUMP_CONFIG WHERE ELEMENT_NAME = N'DEGREE_OF_TASK_PARALLELISM';
	SELECT @outMax_Threads_In_Pool		= NUMBER_VALUE FROM TPW_PUMP_CONFIG WHERE ELEMENT_NAME = N'MAX_THREADS_IN_POOL';
