CREATE PROCEDURE dbo.TPW_SERVICE_NEXT_TASK_ID
(
	@inPJob_ID	INT,
	@outTask_ID	SMALLINT	OUTPUT
)
AS
	SET NOCOUNT ON;
	DECLARE	@tTableVar	TABLE (TASK_ID	SMALLINT);

	UPDATE	TPW_PJOB
	SET		TASK_ID_RECORD	= TASK_ID_RECORD + 1
	OUTPUT	INSERTED.TASK_ID_RECORD
	INTO	@tTableVar (TASK_ID)
	WHERE	PJOB_ID	= @inPJob_ID;

	SELECT	@outTask_ID = TASK_ID	FROM @tTableVar;
