CREATE OR REPLACE TRIGGER XYZ.TRG_TPW_WF_ACTIVITY
BEFORE INSERT OR UPDATE ON XYZ.TPW_WF_ACTIVITY
FOR EACH ROW
BEGIN
	XYZ.TPW_SERVICE.CHECK_STATE_ID_NAME(:new.BEGIN_STATE_ID, :new.ACTIVITY, :new.BEGIN_STATE_NAME);
	XYZ.TPW_SERVICE.CHECK_STATE_ID_NAME(:new.END_STATE_ID, :new.ACTIVITY, :new.END_STATE_NAME);
END;
