CREATE FUNCTION dbo.TPW_SERVICE_GET_EXPIRY_DAY
(
)
RETURNS	TINYINT
AS
BEGIN
	DECLARE	@Expiry_Day		TINYINT;

	SELECT	@Expiry_Day = NUMBER_VALUE
	FROM	TPW_PUMP_CONFIG
	WHERE	ELEMENT_NAME = N'EXPIRY_DAY';

	RETURN	@Expiry_Day;
END;
