CREATE FUNCTION dbo.TPW_SERVICE_GET_EXPIRE_INTERVAL
(
)
RETURNS	TINYINT
AS
BEGIN
	DECLARE	@Expire_Interval	TINYINT;

	SELECT	@Expire_Interval = NUMBER_VALUE
	FROM	TPW_PUMP_CONFIG
	WHERE	ELEMENT_NAME = N'EXPIRE_INTERVAL';

	RETURN	@Expire_Interval;
END;
