CREATE FUNCTION dbo.TPW_SERVICE_GET_STANDBY_INTERVAL
(
)
RETURNS	TINYINT
AS
BEGIN
	DECLARE	@Standby_Interval	TINYINT;

	SELECT	@Standby_Interval = NUMBER_VALUE
	FROM	TPW_PUMP_CONFIG
	WHERE	ELEMENT_NAME = N'STANDBY_INTERVAL';

	RETURN	@Standby_Interval;
END;
