CREATE FUNCTION dbo.TPW_SERVICE_GET_ARCHIVE_INTERVAL
(
)
RETURNS	TINYINT
AS
BEGIN
	DECLARE	@Archive_Interval	TINYINT;

	SELECT	@Archive_Interval = NUMBER_VALUE
	FROM	TPW_PUMP_CONFIG
	WHERE	ELEMENT_NAME = N'ARCHIVE_INTERVAL';

	RETURN	@Archive_Interval;
END;
