-- This reset data query can be run if you are sure all existing data are test data.

TRUNCATE TABLE XYZ.TPW_SYS_ERROR;
TRUNCATE TABLE XYZ.TPW_PUMP_SERVER;
TRUNCATE TABLE XYZ.TPW_WK_LOG;
TRUNCATE TABLE XYZ.TPW_WK_LOG_ARCHIVE;

DELETE FROM XYZ.TPW_PJOB;
DELETE FROM XYZ.TPW_PJOB_ARCHIVE;

UPDATE	XYZ.TPW_PUMP_CONFIG
SET		DATE_VALUE	= '2012-01-01'
WHERE	DATE_VALUE	IS NOT NULL;

UPDATE	XYZ.TPW_PUMP_CONFIG
SET		NUMBER_VALUE	= 1
WHERE	ELEMENT_NAME	= 'PJOB_ID_RECORD';

COMMIT;
