-- CREATE TABLE
CREATE TABLE XYZ.TPW_PUMP_CONFIG
(
	ELEMENT_NAME		VARCHAR2(32) NOT NULL,
	NUMBER_VALUE		NUMBER,
	DATE_VALUE			DATE,
	STRING_VALUE		VARCHAR2(256),
	DESCRIPTION_		VARCHAR2(256),
	CONSTRAINT PK_TPW_PUMP_CONFIG PRIMARY KEY (ELEMENT_NAME),
	CONSTRAINT CK_TPW_PUMP_CONFIG_VALUE CHECK (NUMBER_VALUE IS NOT NULL OR DATE_VALUE IS NOT NULL OR STRING_VALUE IS NOT NULL)
)
ORGANIZATION INDEX
STORAGE (INITIAL 16K NEXT 8K);
