-- CREATE TABLE
CREATE TABLE XYZ.TPW_WF_ACTIVITY
(
	ACTIVITY			VARCHAR2(32)	NOT NULL,
	DESCRIPTION_		VARCHAR2(256),
	BEGIN_STATE_ID		NUMBER(5),
	BEGIN_STATE_NAME	VARCHAR2(32),
	END_STATE_ID		NUMBER(5),
	END_STATE_NAME		VARCHAR2(32),
	CONSTRAINT PK_TPW_WF_ACTIVITY PRIMARY KEY (ACTIVITY)
)
ORGANIZATION INDEX
STORAGE (INITIAL 16K NEXT 8K);
