-- CREATE TABLE
CREATE TABLE XYZ.TPW_WF_STATE
(
	STATE_ID			NUMBER(5)		NOT NULL,
	ACTIVITY			VARCHAR2(32)	NOT NULL,
	STATE_NAME			VARCHAR2(32)	NOT NULL,
	DESCRIPTION_		VARCHAR2(256),
	CONSTRAINT PK_TPW_WF_STATE PRIMARY KEY (STATE_ID),
	CONSTRAINT UK_TPW_WF_STATE UNIQUE (ACTIVITY, STATE_NAME),
	CONSTRAINT FK_TPW_WF_STATE_ACTIVITY FOREIGN KEY (ACTIVITY) REFERENCES XYZ.TPW_WF_ACTIVITY (ACTIVITY)
)
ORGANIZATION INDEX
STORAGE (INITIAL 64K NEXT 64K);
