-- CREATE TABLE
CREATE TABLE XYZ.TPW_WF_EVENT
(
	EVENT_ID			NUMBER(5)		NOT NULL,
	ACTIVITY			VARCHAR2(32)	NOT NULL,
	EVENT_NAME			VARCHAR2(32)	NOT NULL,
	DESCRIPTION_		VARCHAR2(256),
	CONSTRAINT PK_TPW_WF_EVENT PRIMARY KEY (EVENT_ID),
	CONSTRAINT UK_TPW_WF_EVENT UNIQUE (ACTIVITY, EVENT_NAME),
	CONSTRAINT FK_TPW_WF_EVENT_ACTIVITY FOREIGN KEY (ACTIVITY) REFERENCES XYZ.TPW_WF_ACTIVITY (ACTIVITY)
)
ORGANIZATION INDEX
STORAGE (INITIAL 32K NEXT 32K);
