-- Create/Recreate primary, unique and foreign key constraints
ALTER TABLE XYZ.TPW_WF_ACTIVITY ADD CONSTRAINT FK_TPW_WF_ACTIVITY_SID0 FOREIGN KEY (BEGIN_STATE_ID) REFERENCES XYZ.TPW_WF_STATE (STATE_ID);
ALTER TABLE XYZ.TPW_WF_ACTIVITY ADD CONSTRAINT FK_TPW_WF_ACTIVITY_SID1 FOREIGN KEY (END_STATE_ID) REFERENCES XYZ.TPW_WF_STATE (STATE_ID);
ALTER TABLE XYZ.TPW_WF_ACTIVITY ADD CONSTRAINT FK_TPW_WF_ACTIVITY_SN0 FOREIGN KEY (ACTIVITY, BEGIN_STATE_NAME) REFERENCES XYZ.TPW_WF_STATE (ACTIVITY, STATE_NAME);
ALTER TABLE XYZ.TPW_WF_ACTIVITY ADD CONSTRAINT FK_TPW_WF_ACTIVITY_SN1 FOREIGN KEY (ACTIVITY, END_STATE_NAME) REFERENCES XYZ.TPW_WF_STATE (ACTIVITY, STATE_NAME);
