-- CREATE TABLE
CREATE TABLE XYZ.TPW_WK_LOG
(
	LOG_TIME			TIMESTAMP(3)	NOT NULL,
	REFER_ID			NUMBER(10)		NOT NULL,

	STATE_ID_OLD		NUMBER(5),
	EVENT_ID			NUMBER(5),
	STATE_ID_NEW		NUMBER(5)		NOT NULL,

	MESSAGE_			VARCHAR2(1024)
)
STORAGE (INITIAL 1M NEXT 1M);
