-- CREATE TABLE
CREATE TABLE XYZ.TPW_PJOB_ARCHIVE
(
	PJOB_ID				NUMBER(10)		NOT NULL,
	STATE_ID			NUMBER(5)		NOT NULL,
	TASK_ID_RECORD		NUMBER(5)		NOT NULL,
	SCHEDULED_TIME		DATE			NOT NULL,
	EXPIRY_TIME			DATE			NOT NULL,
	START_TIME			TIMESTAMP(3),
	END_TIME			TIMESTAMP(3),
	USER_APP			VARCHAR2(128),
	USER_NAME			VARCHAR2(64),
	DESCRIPTION_		VARCHAR2(256),

	CONSTRAINT PK_TPW_PJOB_ARCHIVE PRIMARY KEY (PJOB_ID),
	CONSTRAINT FK_TPW_PJOB_ARCHIVE_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES XYZ.TPW_WF_STATE (STATE_ID)
)
STORAGE (INITIAL 4M NEXT 4M)
COMPRESS FOR ALL OPERATIONS;
