-- CREATE TABLE
CREATE TABLE XYZ.TPW_TASK_ARCHIVE
(
	PJOB_ID				NUMBER(10)						NOT NULL,
	TASK_ID				NUMBER(5)						NOT NULL,
	COMMAND_TIMEOUT		NUMBER(3)						NOT NULL,		-- Minutes
	DYNAMIC_SQL_STMT	CLOB							NOT NULL,
	DESCRIPTION_		VARCHAR2(256),
	START_TIME			TIMESTAMP(3),
	END_TIME			TIMESTAMP(3),
	ERROR_MESSAGE		VARCHAR2(256),

	CONSTRAINT PK_TPW_TASK_ARCHIVE PRIMARY KEY (PJOB_ID, TASK_ID),
	CONSTRAINT FK_TPW_TASK_ARCHIVE_PJOB_ID FOREIGN KEY (PJOB_ID) REFERENCES XYZ.TPW_PJOB_ARCHIVE (PJOB_ID) ON DELETE CASCADE
)
STORAGE (INITIAL 8M NEXT 8M)
COMPRESS FOR ALL OPERATIONS;

COMMENT ON COLUMN XYZ.TPW_TASK_ARCHIVE.TASK_ID IS '0: reserved for Callback after Success; -1: reserved for Callback after Fail;';
