CREATE TABLE TPW_WF_EVENT
(
	EVENT_ID			SMALLINT		NOT NULL,
	ACTIVITY			NVARCHAR(32)	NOT NULL,
	EVENT_NAME			NVARCHAR(32)	NOT NULL,
	DESCRIPTION_		NVARCHAR(256),

	CONSTRAINT PK_TPW_WF_EVENT PRIMARY KEY (EVENT_ID),
	CONSTRAINT UK_TPW_WF_EVENT UNIQUE (ACTIVITY, EVENT_NAME),
	CONSTRAINT FK_TPW_WF_EVENT_ACTIVITY FOREIGN KEY (ACTIVITY) REFERENCES TPW_WF_ACTIVITY (ACTIVITY)
);
