CREATE TABLE TPW_WF_STATE
(
	STATE_ID			SMALLINT		NOT NULL,
	ACTIVITY			NVARCHAR(32)	NOT NULL,
	STATE_NAME			NVARCHAR(32)	NOT NULL,
	DESCRIPTION_		NVARCHAR(256),
	CONSTRAINT PK_TPW_WF_STATE PRIMARY KEY (STATE_ID),
	CONSTRAINT UK_TPW_WF_STATE UNIQUE (ACTIVITY, STATE_NAME),
	CONSTRAINT FK_TPW_WF_STATE_ACTIVITY FOREIGN KEY (ACTIVITY) REFERENCES TPW_WF_ACTIVITY (ACTIVITY)
);
