CREATE TABLE TPW_PJOB_ARCHIVE
(
	PJOB_ID				INT				NOT NULL,
	STATE_ID			SMALLINT		NOT NULL,
	TASK_ID_RECORD		SMALLINT		NOT NULL,
	SCHEDULED_TIME		DATETIME		NOT NULL,
	EXPIRY_TIME			DATETIME		NOT NULL,
	START_TIME			DATETIME,
	END_TIME			DATETIME,
	USER_APP			NVARCHAR(128),
	USER_NAME			NVARCHAR(64),
	DESCRIPTION_		NVARCHAR(256),

	CONSTRAINT PK_TPW_PJOB_ARCHIVE PRIMARY KEY (PJOB_ID),
	CONSTRAINT FK_TPW_PJOB_ARCHIVE_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES TPW_WF_STATE (STATE_ID)
);
