CREATE TABLE TPW_PJOB
(
	PJOB_ID				INT										NOT NULL,
	STATE_ID			SMALLINT								NOT NULL,
	TASK_ID_RECORD		SMALLINT		DEFAULT 0				NOT NULL,
	SCHEDULED_TIME		DATETIME		DEFAULT GETDATE()		NOT NULL,
	EXPIRY_TIME			DATETIME		DEFAULT (GETDATE()+7)	NOT NULL,
	START_TIME			DATETIME,
	END_TIME			DATETIME,
	USER_APP			NVARCHAR(128),
	USER_NAME			NVARCHAR(64),
	DESCRIPTION_		NVARCHAR(256),

	CONSTRAINT PK_TPW_PJOB PRIMARY KEY (PJOB_ID),
	CONSTRAINT FK_TPW_PJOB_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES TPW_WF_STATE (STATE_ID),
	CONSTRAINT CK_TPW_PJOB_TASK_ID_RECORD CHECK (TASK_ID_RECORD >= 0)
);
