CREATE TABLE TPW_PUMP_CONFIG
(
	ELEMENT_NAME		NVARCHAR(32) NOT NULL,
	NUMBER_VALUE		INT,
	DATE_VALUE			DATETIME,
	STRING_VALUE		NVARCHAR(256),
	DESCRIPTION_		NVARCHAR(256),

	CONSTRAINT PK_TPW_PUMP_CONFIG PRIMARY KEY (ELEMENT_NAME),
	CONSTRAINT CK_TPW_PUMP_CONFIG_VALUE CHECK (NUMBER_VALUE IS NOT NULL OR DATE_VALUE IS NOT NULL OR STRING_VALUE IS NOT NULL)
);
