CREATE TABLE TPW_TASK_ARCHIVE
(
	PJOB_ID				INT				NOT NULL,
	TASK_ID				SMALLINT		NOT NULL,
	COMMAND_TIMEOUT		TINYINT			NOT NULL,		-- Minutes
	DYNAMIC_SQL_STMT	NVARCHAR(MAX)	NOT NULL,
	DESCRIPTION_		NVARCHAR(256),
	START_TIME			DATETIME,
	END_TIME			DATETIME,
	ERROR_MESSAGE		NVARCHAR(256),

	CONSTRAINT PK_TPW_TASK_ARCHIVE PRIMARY KEY (PJOB_ID, TASK_ID),
	CONSTRAINT FK_TPW_TASK_ARCHIVE_PJOB_ID FOREIGN KEY (PJOB_ID) REFERENCES TPW_PJOB_ARCHIVE (PJOB_ID) ON DELETE CASCADE
);
